import { ref, watch } from 'vue';
import { useRouter } from 'vue-router';
import { NLayout, NLayoutContent, NCard, NForm, NFormItem, NInput, NButton, useMessage } from 'naive-ui';
import api from '../api';
import { MoonOutline, SunnyOutline } from '@vicons/ionicons5';
const __VLS_props = defineProps();
const __VLS_emit = defineEmits(['toggle-theme']);
const message = useMessage();
const router = useRouter();
const form = ref({
    name: '',
    full_name: '',
    email: '',
    password: '',
    confirmPassword: '',
    emp_id: null,
    role_type: 'staff' // default selection
});
const rules = {
    name: [{ required: true, message: 'Username is required' }],
    full_name: [{ required: true, message: 'Full Name is required' }],
    email: [
        {
            validator: (_, value) => {
                if (value && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)) {
                    return new Error('Please enter a valid email address');
                }
                return true;
            },
            trigger: ['input', 'blur']
        }
    ],
    password: [{ required: true, message: 'Password is required' }],
    confirmPassword: [
        { required: true, message: 'Confirm password is required' },
        {
            validator: (_, value) => value === form.value.password,
            message: 'Passwords do not match',
            trigger: ['input', 'blur']
        }
    ],
    emp_id: [
        {
            validator: (_rule, value) => {
                // allow `null` or `undefined` (i.e. no entry)
                if (value === null || value === undefined) {
                    return true;
                }
                // otherwise enforce integer
                return Number.isInteger(value);
            },
            message: 'Employee ID must be a number',
            trigger: ['input', 'blur']
        }
    ]
};
const autoGeneratedName = ref(true);
watch(() => form.value.full_name, (newVal) => {
    if (!newVal?.trim()) {
        if (autoGeneratedName.value)
            form.value.name = '';
        return;
    }
    const suggested = newVal.replace(/[^a-zA-Z0-9]/g, '').toLowerCase();
    if (autoGeneratedName.value || !form.value.name) {
        form.value.name = suggested;
        autoGeneratedName.value = true;
    }
});
watch(() => form.value.name, (newVal) => {
    const expected = form.value.full_name?.replace(/[^a-zA-Z0-9]/g, '').toLowerCase() || '';
    if (newVal !== expected) {
        autoGeneratedName.value = false;
    }
});
const formRef = ref();
const handleSignup = async () => {
    try {
        await formRef.value?.validate();
        const payload = {
            ...form.value,
            emp_id: form.value.emp_id ? Number(form.value.emp_id) : null,
            role_id: 3 // Default role for signups
        };
        delete payload.confirmPassword;
        const res = await api.post('/api/signup', payload);
        message.success(`Account for ${form.value.name} created successfully!`);
        setTimeout(() => {
            window.location.href = '/login';
        }, 1000);
    }
    catch (err) {
        if (err.response) {
            message.error(err.response.data.error || 'Signup failed');
        }
        else {
            message.error('Please fill all required fields correctly');
        }
    }
};
debugger; /* PartiallyEnd: #3632/scriptSetup.vue */
const __VLS_ctx = {};
let __VLS_components;
let __VLS_directives;
// CSS variable injection 
// CSS variable injection end 
const __VLS_0 = {}.NLayout;
/** @type {[typeof __VLS_components.NLayout, typeof __VLS_components.nLayout, typeof __VLS_components.NLayout, typeof __VLS_components.nLayout, ]} */ ;
// @ts-ignore
const __VLS_1 = __VLS_asFunctionalComponent(__VLS_0, new __VLS_0({}));
const __VLS_2 = __VLS_1({}, ...__VLS_functionalComponentArgsRest(__VLS_1));
var __VLS_4 = {};
__VLS_3.slots.default;
__VLS_asFunctionalElement(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({
    ...{ class: "top-bar" },
});
const __VLS_5 = {}.NButton;
/** @type {[typeof __VLS_components.NButton, typeof __VLS_components.nButton, typeof __VLS_components.NButton, typeof __VLS_components.nButton, ]} */ ;
// @ts-ignore
const __VLS_6 = __VLS_asFunctionalComponent(__VLS_5, new __VLS_5({
    ...{ 'onClick': {} },
    quaternary: true,
    circle: true,
    size: "large",
    ...{ class: "theme-toggle-btn" },
}));
const __VLS_7 = __VLS_6({
    ...{ 'onClick': {} },
    quaternary: true,
    circle: true,
    size: "large",
    ...{ class: "theme-toggle-btn" },
}, ...__VLS_functionalComponentArgsRest(__VLS_6));
let __VLS_9;
let __VLS_10;
let __VLS_11;
const __VLS_12 = {
    onClick: (...[$event]) => {
        __VLS_ctx.$emit('toggle-theme');
    }
};
__VLS_8.slots.default;
const __VLS_13 = {}.NIcon;
/** @type {[typeof __VLS_components.NIcon, typeof __VLS_components.nIcon, ]} */ ;
// @ts-ignore
const __VLS_14 = __VLS_asFunctionalComponent(__VLS_13, new __VLS_13({
    component: (__VLS_ctx.isDark ? __VLS_ctx.SunnyOutline : __VLS_ctx.MoonOutline),
}));
const __VLS_15 = __VLS_14({
    component: (__VLS_ctx.isDark ? __VLS_ctx.SunnyOutline : __VLS_ctx.MoonOutline),
}, ...__VLS_functionalComponentArgsRest(__VLS_14));
var __VLS_8;
const __VLS_17 = {}.NLayoutContent;
/** @type {[typeof __VLS_components.NLayoutContent, typeof __VLS_components.nLayoutContent, typeof __VLS_components.NLayoutContent, typeof __VLS_components.nLayoutContent, ]} */ ;
// @ts-ignore
const __VLS_18 = __VLS_asFunctionalComponent(__VLS_17, new __VLS_17({
    ...{ class: "signup-wrapper" },
}));
const __VLS_19 = __VLS_18({
    ...{ class: "signup-wrapper" },
}, ...__VLS_functionalComponentArgsRest(__VLS_18));
__VLS_20.slots.default;
__VLS_asFunctionalElement(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({
    ...{ class: "form-container" },
});
const __VLS_21 = {}.NCard;
/** @type {[typeof __VLS_components.NCard, typeof __VLS_components.nCard, typeof __VLS_components.NCard, typeof __VLS_components.nCard, ]} */ ;
// @ts-ignore
const __VLS_22 = __VLS_asFunctionalComponent(__VLS_21, new __VLS_21({
    ...{ class: "signup-card" },
    title: "Create Your Account",
    bordered: true,
}));
const __VLS_23 = __VLS_22({
    ...{ class: "signup-card" },
    title: "Create Your Account",
    bordered: true,
}, ...__VLS_functionalComponentArgsRest(__VLS_22));
__VLS_24.slots.default;
const __VLS_25 = {}.NForm;
/** @type {[typeof __VLS_components.NForm, typeof __VLS_components.nForm, typeof __VLS_components.NForm, typeof __VLS_components.nForm, ]} */ ;
// @ts-ignore
const __VLS_26 = __VLS_asFunctionalComponent(__VLS_25, new __VLS_25({
    model: (__VLS_ctx.form),
    rules: (__VLS_ctx.rules),
    ref: "formRef",
}));
const __VLS_27 = __VLS_26({
    model: (__VLS_ctx.form),
    rules: (__VLS_ctx.rules),
    ref: "formRef",
}, ...__VLS_functionalComponentArgsRest(__VLS_26));
/** @type {typeof __VLS_ctx.formRef} */ ;
var __VLS_29 = {};
__VLS_28.slots.default;
__VLS_asFunctionalElement(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({
    ...{ class: "form-grid" },
});
const __VLS_31 = {}.NFormItem;
/** @type {[typeof __VLS_components.NFormItem, typeof __VLS_components.nFormItem, typeof __VLS_components.NFormItem, typeof __VLS_components.nFormItem, ]} */ ;
// @ts-ignore
const __VLS_32 = __VLS_asFunctionalComponent(__VLS_31, new __VLS_31({
    label: "Full Name",
    path: "full_name",
}));
const __VLS_33 = __VLS_32({
    label: "Full Name",
    path: "full_name",
}, ...__VLS_functionalComponentArgsRest(__VLS_32));
__VLS_34.slots.default;
const __VLS_35 = {}.NInput;
/** @type {[typeof __VLS_components.NInput, typeof __VLS_components.nInput, ]} */ ;
// @ts-ignore
const __VLS_36 = __VLS_asFunctionalComponent(__VLS_35, new __VLS_35({
    value: (__VLS_ctx.form.full_name),
    placeholder: "Your name",
    clearable: true,
}));
const __VLS_37 = __VLS_36({
    value: (__VLS_ctx.form.full_name),
    placeholder: "Your name",
    clearable: true,
}, ...__VLS_functionalComponentArgsRest(__VLS_36));
var __VLS_34;
const __VLS_39 = {}.NFormItem;
/** @type {[typeof __VLS_components.NFormItem, typeof __VLS_components.nFormItem, typeof __VLS_components.NFormItem, typeof __VLS_components.nFormItem, ]} */ ;
// @ts-ignore
const __VLS_40 = __VLS_asFunctionalComponent(__VLS_39, new __VLS_39({
    label: "Username",
    path: "name",
}));
const __VLS_41 = __VLS_40({
    label: "Username",
    path: "name",
}, ...__VLS_functionalComponentArgsRest(__VLS_40));
__VLS_42.slots.default;
const __VLS_43 = {}.NInput;
/** @type {[typeof __VLS_components.NInput, typeof __VLS_components.nInput, ]} */ ;
// @ts-ignore
const __VLS_44 = __VLS_asFunctionalComponent(__VLS_43, new __VLS_43({
    value: (__VLS_ctx.form.name),
    placeholder: "Preferred username",
    clearable: true,
}));
const __VLS_45 = __VLS_44({
    value: (__VLS_ctx.form.name),
    placeholder: "Preferred username",
    clearable: true,
}, ...__VLS_functionalComponentArgsRest(__VLS_44));
var __VLS_42;
const __VLS_47 = {}.NFormItem;
/** @type {[typeof __VLS_components.NFormItem, typeof __VLS_components.nFormItem, typeof __VLS_components.NFormItem, typeof __VLS_components.nFormItem, ]} */ ;
// @ts-ignore
const __VLS_48 = __VLS_asFunctionalComponent(__VLS_47, new __VLS_47({
    label: "User Type",
}));
const __VLS_49 = __VLS_48({
    label: "User Type",
}, ...__VLS_functionalComponentArgsRest(__VLS_48));
__VLS_50.slots.default;
const __VLS_51 = {}.NRadioGroup;
/** @type {[typeof __VLS_components.NRadioGroup, typeof __VLS_components.nRadioGroup, typeof __VLS_components.NRadioGroup, typeof __VLS_components.nRadioGroup, ]} */ ;
// @ts-ignore
const __VLS_52 = __VLS_asFunctionalComponent(__VLS_51, new __VLS_51({
    value: (__VLS_ctx.form.role_type),
}));
const __VLS_53 = __VLS_52({
    value: (__VLS_ctx.form.role_type),
}, ...__VLS_functionalComponentArgsRest(__VLS_52));
__VLS_54.slots.default;
const __VLS_55 = {}.NRadio;
/** @type {[typeof __VLS_components.NRadio, typeof __VLS_components.nRadio, typeof __VLS_components.NRadio, typeof __VLS_components.nRadio, ]} */ ;
// @ts-ignore
const __VLS_56 = __VLS_asFunctionalComponent(__VLS_55, new __VLS_55({
    value: "staff",
}));
const __VLS_57 = __VLS_56({
    value: "staff",
}, ...__VLS_functionalComponentArgsRest(__VLS_56));
__VLS_58.slots.default;
var __VLS_58;
const __VLS_59 = {}.NRadio;
/** @type {[typeof __VLS_components.NRadio, typeof __VLS_components.nRadio, typeof __VLS_components.NRadio, typeof __VLS_components.nRadio, ]} */ ;
// @ts-ignore
const __VLS_60 = __VLS_asFunctionalComponent(__VLS_59, new __VLS_59({
    value: "others",
}));
const __VLS_61 = __VLS_60({
    value: "others",
}, ...__VLS_functionalComponentArgsRest(__VLS_60));
__VLS_62.slots.default;
var __VLS_62;
var __VLS_54;
var __VLS_50;
if (__VLS_ctx.form.role_type === 'staff') {
    const __VLS_63 = {}.NFormItem;
    /** @type {[typeof __VLS_components.NFormItem, typeof __VLS_components.nFormItem, typeof __VLS_components.NFormItem, typeof __VLS_components.nFormItem, ]} */ ;
    // @ts-ignore
    const __VLS_64 = __VLS_asFunctionalComponent(__VLS_63, new __VLS_63({
        label: "Employee ID",
        path: "emp_id",
    }));
    const __VLS_65 = __VLS_64({
        label: "Employee ID",
        path: "emp_id",
    }, ...__VLS_functionalComponentArgsRest(__VLS_64));
    __VLS_66.slots.default;
    const __VLS_67 = {}.NInputNumber;
    /** @type {[typeof __VLS_components.NInputNumber, typeof __VLS_components.nInputNumber, ]} */ ;
    // @ts-ignore
    const __VLS_68 = __VLS_asFunctionalComponent(__VLS_67, new __VLS_67({
        value: (__VLS_ctx.form.emp_id),
        placeholder: "Enter employee ID",
        integer: (true),
        min: (1),
        clearable: true,
        inputProps: ({ inputmode: 'numeric', pattern: '[0-9]*' }),
    }));
    const __VLS_69 = __VLS_68({
        value: (__VLS_ctx.form.emp_id),
        placeholder: "Enter employee ID",
        integer: (true),
        min: (1),
        clearable: true,
        inputProps: ({ inputmode: 'numeric', pattern: '[0-9]*' }),
    }, ...__VLS_functionalComponentArgsRest(__VLS_68));
    var __VLS_66;
}
const __VLS_71 = {}.NFormItem;
/** @type {[typeof __VLS_components.NFormItem, typeof __VLS_components.nFormItem, typeof __VLS_components.NFormItem, typeof __VLS_components.nFormItem, ]} */ ;
// @ts-ignore
const __VLS_72 = __VLS_asFunctionalComponent(__VLS_71, new __VLS_71({
    label: "Email",
    path: "email",
}));
const __VLS_73 = __VLS_72({
    label: "Email",
    path: "email",
}, ...__VLS_functionalComponentArgsRest(__VLS_72));
__VLS_74.slots.default;
const __VLS_75 = {}.NInput;
/** @type {[typeof __VLS_components.NInput, typeof __VLS_components.nInput, ]} */ ;
// @ts-ignore
const __VLS_76 = __VLS_asFunctionalComponent(__VLS_75, new __VLS_75({
    value: (__VLS_ctx.form.email),
    placeholder: "Your email address",
    type: "text",
    clearable: true,
}));
const __VLS_77 = __VLS_76({
    value: (__VLS_ctx.form.email),
    placeholder: "Your email address",
    type: "text",
    clearable: true,
}, ...__VLS_functionalComponentArgsRest(__VLS_76));
var __VLS_74;
const __VLS_79 = {}.NFormItem;
/** @type {[typeof __VLS_components.NFormItem, typeof __VLS_components.nFormItem, typeof __VLS_components.NFormItem, typeof __VLS_components.nFormItem, ]} */ ;
// @ts-ignore
const __VLS_80 = __VLS_asFunctionalComponent(__VLS_79, new __VLS_79({
    label: "Password",
    path: "password",
}));
const __VLS_81 = __VLS_80({
    label: "Password",
    path: "password",
}, ...__VLS_functionalComponentArgsRest(__VLS_80));
__VLS_82.slots.default;
const __VLS_83 = {}.NInput;
/** @type {[typeof __VLS_components.NInput, typeof __VLS_components.nInput, ]} */ ;
// @ts-ignore
const __VLS_84 = __VLS_asFunctionalComponent(__VLS_83, new __VLS_83({
    type: "password",
    value: (__VLS_ctx.form.password),
    placeholder: "Choose a password",
    clearable: true,
}));
const __VLS_85 = __VLS_84({
    type: "password",
    value: (__VLS_ctx.form.password),
    placeholder: "Choose a password",
    clearable: true,
}, ...__VLS_functionalComponentArgsRest(__VLS_84));
var __VLS_82;
const __VLS_87 = {}.NFormItem;
/** @type {[typeof __VLS_components.NFormItem, typeof __VLS_components.nFormItem, typeof __VLS_components.NFormItem, typeof __VLS_components.nFormItem, ]} */ ;
// @ts-ignore
const __VLS_88 = __VLS_asFunctionalComponent(__VLS_87, new __VLS_87({
    label: "Confirm Password",
    path: "confirmPassword",
}));
const __VLS_89 = __VLS_88({
    label: "Confirm Password",
    path: "confirmPassword",
}, ...__VLS_functionalComponentArgsRest(__VLS_88));
__VLS_90.slots.default;
const __VLS_91 = {}.NInput;
/** @type {[typeof __VLS_components.NInput, typeof __VLS_components.nInput, ]} */ ;
// @ts-ignore
const __VLS_92 = __VLS_asFunctionalComponent(__VLS_91, new __VLS_91({
    type: "password",
    value: (__VLS_ctx.form.confirmPassword),
    placeholder: "Re-enter password",
    clearable: true,
}));
const __VLS_93 = __VLS_92({
    type: "password",
    value: (__VLS_ctx.form.confirmPassword),
    placeholder: "Re-enter password",
    clearable: true,
}, ...__VLS_functionalComponentArgsRest(__VLS_92));
var __VLS_90;
const __VLS_95 = {}.NFormItem;
/** @type {[typeof __VLS_components.NFormItem, typeof __VLS_components.nFormItem, typeof __VLS_components.NFormItem, typeof __VLS_components.nFormItem, ]} */ ;
// @ts-ignore
const __VLS_96 = __VLS_asFunctionalComponent(__VLS_95, new __VLS_95({}));
const __VLS_97 = __VLS_96({}, ...__VLS_functionalComponentArgsRest(__VLS_96));
__VLS_98.slots.default;
const __VLS_99 = {}.NButton;
/** @type {[typeof __VLS_components.NButton, typeof __VLS_components.nButton, typeof __VLS_components.NButton, typeof __VLS_components.nButton, ]} */ ;
// @ts-ignore
const __VLS_100 = __VLS_asFunctionalComponent(__VLS_99, new __VLS_99({
    ...{ 'onClick': {} },
    type: "primary",
    block: true,
}));
const __VLS_101 = __VLS_100({
    ...{ 'onClick': {} },
    type: "primary",
    block: true,
}, ...__VLS_functionalComponentArgsRest(__VLS_100));
let __VLS_103;
let __VLS_104;
let __VLS_105;
const __VLS_106 = {
    onClick: (__VLS_ctx.handleSignup)
};
__VLS_102.slots.default;
var __VLS_102;
var __VLS_98;
__VLS_asFunctionalElement(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({
    ...{ style: {} },
});
const __VLS_107 = {}.NButton;
/** @type {[typeof __VLS_components.NButton, typeof __VLS_components.nButton, typeof __VLS_components.NButton, typeof __VLS_components.nButton, ]} */ ;
// @ts-ignore
const __VLS_108 = __VLS_asFunctionalComponent(__VLS_107, new __VLS_107({
    ...{ 'onClick': {} },
    text: true,
}));
const __VLS_109 = __VLS_108({
    ...{ 'onClick': {} },
    text: true,
}, ...__VLS_functionalComponentArgsRest(__VLS_108));
let __VLS_111;
let __VLS_112;
let __VLS_113;
const __VLS_114 = {
    onClick: (...[$event]) => {
        __VLS_ctx.router.push('/login');
    }
};
__VLS_110.slots.default;
var __VLS_110;
var __VLS_28;
var __VLS_24;
var __VLS_20;
var __VLS_3;
/** @type {__VLS_StyleScopedClasses['top-bar']} */ ;
/** @type {__VLS_StyleScopedClasses['theme-toggle-btn']} */ ;
/** @type {__VLS_StyleScopedClasses['signup-wrapper']} */ ;
/** @type {__VLS_StyleScopedClasses['form-container']} */ ;
/** @type {__VLS_StyleScopedClasses['signup-card']} */ ;
/** @type {__VLS_StyleScopedClasses['form-grid']} */ ;
// @ts-ignore
var __VLS_30 = __VLS_29;
var __VLS_dollars;
const __VLS_self = (await import('vue')).defineComponent({
    setup() {
        return {
            NLayout: NLayout,
            NLayoutContent: NLayoutContent,
            NCard: NCard,
            NForm: NForm,
            NFormItem: NFormItem,
            NInput: NInput,
            NButton: NButton,
            MoonOutline: MoonOutline,
            SunnyOutline: SunnyOutline,
            router: router,
            form: form,
            rules: rules,
            formRef: formRef,
            handleSignup: handleSignup,
        };
    },
    emits: {},
    __typeProps: {},
});
export default (await import('vue')).defineComponent({
    setup() {
        return {};
    },
    emits: {},
    __typeProps: {},
});
; /* PartiallyEnd: #4569/main.vue */
//# sourceMappingURL=Signup.vue.js.map